/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tuan2;

import javax.swing.*;
import java.io.*;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author ndthi
 */
public class FormBai31 extends javax.swing.JFrame {

    /**
     * Creates new form FormBai31
     */
    public FormBai31() {
        initComponents();
    }
    

       public class SoNguyenTo {
    boolean kiemtranguyento(int n) {
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcpath = new javax.swing.JFileChooser();
        btndocvanban = new javax.swing.JButton();
        btnghivanban = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnquaylai = new javax.swing.JButton();
        txtpath = new javax.swing.JTextField();
        btnchon = new javax.swing.JButton();
        btnrandom = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt123 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btndocvanban.setText("Đọc File văn bản");
        btndocvanban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocvanbanActionPerformed(evt);
            }
        });

        btnghivanban.setText("Ghi File văn bản");
        btnghivanban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghivanbanActionPerformed(evt);
            }
        });

        jLabel1.setText("Chọn đường dẫn");

        btnquaylai.setText("Quay lại");
        btnquaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaylaiActionPerformed(evt);
            }
        });

        btnchon.setText("Chọn");
        btnchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonActionPerformed(evt);
            }
        });

        btnrandom.setText("Ngẫu Nhiên");
        btnrandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrandomActionPerformed(evt);
            }
        });

        txt123.setColumns(20);
        txt123.setRows(5);
        jScrollPane2.setViewportView(txt123);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnrandom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(txtpath))
                        .addGap(18, 18, 18)
                        .addComponent(btnchon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnquaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))
                            .addComponent(btndocvanban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnghivanban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnrandom)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(btndocvanban)
                .addGap(28, 28, 28)
                .addComponent(btnghivanban)
                .addGap(28, 28, 28)
                .addComponent(btnquaylai)
                .addGap(133, 133, 133))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndocvanbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocvanbanActionPerformed
        // TODO add your handling code here:
try {
            FileReader fr = new FileReader(new File(txtpath.getText()));
            StringBuffer sb = new StringBuffer();
            char ca[] = new char[5];
            while (fr.ready()) {
                int leng = fr.read(ca);
                sb.append(ca, 0, leng);
            }
            fr.close();
           
            txt123.setText(sb + "");
//            String[] ; 
             
            ArrayList<String> mauso = new ArrayList<String>();
            String a = sb.toString();
            for (int i = 0; i < 10 ; i++) {
                String[] parts = a.split("\\n");
                String mau = parts[i];
                System.out.println(mau);
                mauso.add(mau);
            }

            ArrayList<String> psnguyento = new ArrayList<String>();
            SoNguyenTo snt = new SoNguyenTo();
            String maus = null;
            for (int i = 0; i < mauso.size(); i++) {
                String[] b = mauso.get(i).split("/");
                maus = b[1];
                if ((Integer.parseInt(maus)) >1 &&snt.kiemtranguyento(Integer.parseInt(maus))) {
                    psnguyento.add(mauso.get(i));
                    
                    txt123.setText(psnguyento.toString());
                    System.out.println(maus);

                } else {
                    System.out.println("k có số nguyê tố");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "thanh cong");
    }//GEN-LAST:event_btndocvanbanActionPerformed

    private void btnghivanbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghivanbanActionPerformed
//         TODO add your handling code here:
        try {

            FileWriter fw = new FileWriter(new File(txtpath.getText()));
            fw.write(txt123.getText());
            fw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "thanh cong");
    }//GEN-LAST:event_btnghivanbanActionPerformed

    private void btnquaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaylaiActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnquaylaiActionPerformed

    private void btnchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonActionPerformed
        // TODO add your handling code here:
        this.fcpath.setVisible(true);
        fcpath.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (this.fcpath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION);
        {
            try {
                txtpath.setText(fcpath.getSelectedFile().getCanonicalPath());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnchonActionPerformed

    private void btnrandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrandomActionPerformed
        // TODO add your handling code here:
        ArrayList<String> phanso = new ArrayList<String>();
        for (int i = 0; i < 10; i++) {
            Random rand = new Random();
            int tuso = rand.nextInt(100) + 1;
            int mauso = rand.nextInt(100) + 1;
            phanso.add(tuso + "/" + mauso + "\n");
        }
        String customphanso = phanso.toString();
        customphanso = customphanso.substring(1, customphanso.length() - 1);
        customphanso = customphanso.replaceAll(" ", "");
        txt123.setText(customphanso.replaceAll(",", ""));

        String a = "123/456";
        String[] parts = a.split("/");
        String mau = parts[0];
        System.out.println(mau);
    }//GEN-LAST:event_btnrandomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBai31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBai31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBai31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBai31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBai31().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchon;
    private javax.swing.JButton btndocvanban;
    private javax.swing.JButton btnghivanban;
    private javax.swing.JButton btnquaylai;
    private javax.swing.JButton btnrandom;
    private javax.swing.JFileChooser fcpath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt123;
    private javax.swing.JTextField txtpath;
    // End of variables declaration//GEN-END:variables
}
