/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tuan2;

import javax.swing.*;
import java.io.*;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author ndthi
 */
public class FormBai31 extends javax.swing.JFrame {

    /**
     * Creates new form FormBai31
     */
    public FormBai31() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcpath = new javax.swing.JFileChooser();
        btndocvanban = new javax.swing.JButton();
        btnghivanban = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnquaylai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtpath = new javax.swing.JTextField();
        btnchon = new javax.swing.JButton();
        txtnhapchuoi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnoidung = new javax.swing.JTextField();
        btndocnhiphan = new javax.swing.JButton();
        btnghinhiphan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listrandom = new javax.swing.JList<>();
        btnrandom = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt123 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btndocvanban.setText("Đọc File văn bản");
        btndocvanban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocvanbanActionPerformed(evt);
            }
        });

        btnghivanban.setText("Ghi File văn bản");
        btnghivanban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghivanbanActionPerformed(evt);
            }
        });

        jLabel1.setText("Chọn đường dẫn");

        btnquaylai.setText("Quay lại");
        btnquaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaylaiActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập chuỗi");

        btnchon.setText("Chọn");
        btnchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonActionPerformed(evt);
            }
        });

        jLabel3.setText("Nội dung file");

        txtnoidung.setBackground(new java.awt.Color(51, 153, 255));

        btndocnhiphan.setText("Đọc File nhị phân");
        btndocnhiphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocnhiphanActionPerformed(evt);
            }
        });

        btnghinhiphan.setText("Ghi File nhị phân");
        btnghinhiphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghinhiphanActionPerformed(evt);
            }
        });

        listrandom.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listrandom);

        btnrandom.setText("Ngẫu Nhiên");
        btnrandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrandomActionPerformed(evt);
            }
        });

        txt123.setColumns(20);
        txt123.setRows(5);
        jScrollPane2.setViewportView(txt123);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(txtnhapchuoi))
                            .addComponent(txtnoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnquaylai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnghinhiphan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btndocnhiphan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btndocvanban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnghivanban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnrandom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addComponent(txtpath)
                                    .addComponent(jScrollPane1))
                                .addGap(18, 18, 18)
                                .addComponent(btnchon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrandom))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnhapchuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndocnhiphan)
                    .addComponent(btndocvanban))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnghinhiphan)
                    .addComponent(btnghivanban))
                .addGap(28, 28, 28)
                .addComponent(btnquaylai))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndocvanbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocvanbanActionPerformed
        // TODO add your handling code here:
        try {
            FileReader fr = new FileReader(new File(txtpath.getText()));
            StringBuffer sb = new StringBuffer();
            char ca[] = new char[5];
            while (fr.ready()){
                int leng = fr.read(ca);
                sb.append(ca,0,leng);
            }
            fr.close();
            txt123.setText(sb+"");
        }catch (Exception e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"thanh cong");
    }//GEN-LAST:event_btndocvanbanActionPerformed

    private void btnghivanbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghivanbanActionPerformed
//         TODO add your handling code here:
        try {
    
//            String[] myArray = new String[10];
        ArrayList<String> phanso = new ArrayList<String>();
    for (int i = 0; i < listrandom.getModel().getSize(); i++) {
             phanso.add(String.valueOf(listrandom.getModel().getElementAt(i)));
             System.out.println(phanso.toString());
        }
    System.out.println(phanso.toString());
            
            FileWriter fw = new FileWriter(new File(txtpath.getText()));
            fw.write(txt123.getText());
            fw.close();
        }catch (Exception e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"thanh cong");
    }//GEN-LAST:event_btnghivanbanActionPerformed

    private void btnquaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaylaiActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnquaylaiActionPerformed

    private void btnchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonActionPerformed
        // TODO add your handling code here:
        this.fcpath.setVisible(true);
        fcpath.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (this.fcpath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION);
        {
            try {
                txtpath.setText(fcpath.getSelectedFile().getCanonicalPath());
            }catch (IOException e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_btnchonActionPerformed

    private void btndocnhiphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocnhiphanActionPerformed
        // TODO add your handling code here:
        byte a[] = new byte[20];
        File file;
        try {
            file = new File(txtpath.getText());
            FileInputStream fi = new FileInputStream(file);
            fi.read(a);
            fi.close();
            txtnoidung.setText(new String(a));
        }catch (IOException e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"thanh cong");
    }//GEN-LAST:event_btndocnhiphanActionPerformed

    private void btnghinhiphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghinhiphanActionPerformed
        // TODO add your handling code here:
        byte a[] = new byte[20];
        File file;
       
        
        try {
            file = new File(txtpath.getText());
            try (//            FileOutputStream fos = new FileOutputStream(file);
//            BufferedWriter fo = new BufferedWriter(new OutputStreamWriter(fos));
////            fo.write(a);
//            fo.write(a);
//            fo.newLine();
//            fo.close();
                    FileWriter fw = new FileWriter(file)) {
                fw.write(txt123.getText());
            }
        }catch (IOException e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"thanh cong");
    }//GEN-LAST:event_btnghinhiphanActionPerformed

    private void btnrandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrandomActionPerformed
        // TODO add your handling code here:
         ArrayList<String> phanso = new ArrayList<String>();  
        for (int i=0; i<10; i++) {
            Random rand = new Random();
            int tuso = rand.nextInt(100)+1;
            int mauso = rand.nextInt(100)+1;
            phanso.add(tuso +"/"+mauso+"\n");
        }
        String customphanso = phanso.toString();
        customphanso = customphanso.substring(1, customphanso.length()-1);
        customphanso = customphanso.replaceAll(" ", "");
        txt123.setText(customphanso.replaceAll(",", ""));
    }//GEN-LAST:event_btnrandomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBai31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBai31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBai31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBai31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBai31().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchon;
    private javax.swing.JButton btndocnhiphan;
    private javax.swing.JButton btndocvanban;
    private javax.swing.JButton btnghinhiphan;
    private javax.swing.JButton btnghivanban;
    private javax.swing.JButton btnquaylai;
    private javax.swing.JButton btnrandom;
    private javax.swing.JFileChooser fcpath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listrandom;
    private javax.swing.JTextArea txt123;
    private javax.swing.JTextField txtnhapchuoi;
    private javax.swing.JTextField txtnoidung;
    private javax.swing.JTextField txtpath;
    // End of variables declaration//GEN-END:variables
}
