/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tuan2;

import javax.swing.*;
import java.io.*;

/**
 *
 * @author ndthi
 */
public class FormBai2 extends javax.swing.JFrame {

    /**
     * Creates new form FormBai2
     */
    public FormBai2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcpath = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpath = new javax.swing.JTextField();
        btnchon = new javax.swing.JButton();
        txtnhapchuoi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnoidung = new javax.swing.JTextField();
        btndocnhiphan = new javax.swing.JButton();
        btnghinhiphan = new javax.swing.JButton();
        btndocvanban = new javax.swing.JButton();
        btnghivanban = new javax.swing.JButton();
        btnquaylai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nhập tên tập tin");

        jLabel2.setText("Nhập chuỗi");

        btnchon.setText("Chọn");
        btnchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonActionPerformed(evt);
            }
        });

        jLabel3.setText("Nội dung file");

        txtnoidung.setBackground(new java.awt.Color(51, 153, 255));

        btndocnhiphan.setText("Đọc File nhị phân");
        btndocnhiphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocnhiphanActionPerformed(evt);
            }
        });

        btnghinhiphan.setText("Ghi File nhị phân");
        btnghinhiphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghinhiphanActionPerformed(evt);
            }
        });

        btndocvanban.setText("Đọc File văn bản");
        btndocvanban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocvanbanActionPerformed(evt);
            }
        });

        btnghivanban.setText("Ghi File văn bản");
        btnghivanban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghivanbanActionPerformed(evt);
            }
        });

        btnquaylai.setText("Quay lại");
        btnquaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtpath)
                        .addGap(18, 18, 18)
                        .addComponent(btnchon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnhapchuoi, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(txtnoidung)
                            .addComponent(btnquaylai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnghinhiphan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndocnhiphan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndocvanban, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnghivanban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchon))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnhapchuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndocnhiphan)
                    .addComponent(btndocvanban))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnghinhiphan)
                    .addComponent(btnghivanban))
                .addGap(28, 28, 28)
                .addComponent(btnquaylai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonActionPerformed
        // TODO add your handling code here:
        this.fcpath.setVisible(true);
        fcpath.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (this.fcpath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION);
        {
            try {
                txtpath.setText(fcpath.getSelectedFile().getCanonicalPath());
            }catch (IOException e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_btnchonActionPerformed

    private void btndocnhiphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocnhiphanActionPerformed
        // TODO add your handling code here:
        byte a[] = new byte[20];
        File file;
        try {
            file = new File(txtpath.getText());
            FileInputStream fi = new FileInputStream(file);
            fi.read(a);
            fi.close();
            txtnoidung.setText(new String(a));
        }catch (IOException e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"thanh cong");
    }//GEN-LAST:event_btndocnhiphanActionPerformed

    private void btnghinhiphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghinhiphanActionPerformed
        // TODO add your handling code here:
        byte a[] = new byte[20];
        File file;
        int i;
        char s[] = txtnhapchuoi.getText().toCharArray();
        for (i=0;i<s.length;i++){
            a[i] = (byte) s[i];
        }
        try {
            file = new File(txtpath.getText());
            FileOutputStream fo = new FileOutputStream(file);
            fo.write(a);
            fo.close();
        }catch (IOException e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"thanh cong");
    }//GEN-LAST:event_btnghinhiphanActionPerformed

    private void btndocvanbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocvanbanActionPerformed
        // TODO add your handling code here:
        try {
            FileReader fr = new FileReader(new File(txtpath.getText()));
            StringBuffer sb = new StringBuffer();
            char ca[] = new char[5];
            while (fr.ready()){
                int leng = fr.read(ca);
                sb.append(ca,0,leng);
            }
            fr.close();
            txtnoidung.setText(sb+"");
        }catch (Exception e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"thanh cong");
    }//GEN-LAST:event_btndocvanbanActionPerformed

    private void btnghivanbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghivanbanActionPerformed
        // TODO add your handling code here:
        try {
            FileWriter fw = new FileWriter(new File(txtpath.getText()));
            fw.write(txtnhapchuoi.getText());
            fw.close();
        }catch (Exception e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"thanh cong");

    }//GEN-LAST:event_btnghivanbanActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnquaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaylaiActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnquaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchon;
    private javax.swing.JButton btndocnhiphan;
    private javax.swing.JButton btndocvanban;
    private javax.swing.JButton btnghinhiphan;
    private javax.swing.JButton btnghivanban;
    private javax.swing.JButton btnquaylai;
    private javax.swing.JFileChooser fcpath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtnhapchuoi;
    private javax.swing.JTextField txtnoidung;
    private javax.swing.JTextField txtpath;
    // End of variables declaration//GEN-END:variables
}
