/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package T7.B1;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;

/**
 *
 * @author ndthi
 */
public class rmiClient extends javax.swing.JFrame {

    /**
     * Creates new form rmiClient
     */
    public rmiClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        txtso1 = new javax.swing.JTextField();
        txtso2 = new javax.swing.JTextField();
        txtketqua = new javax.swing.JTextField();
        txtphandu = new javax.swing.JTextField();
        txttua = new javax.swing.JTextField();
        txtmaua = new javax.swing.JTextField();
        txttub = new javax.swing.JTextField();
        txtmaub = new javax.swing.JTextField();
        btnnhan = new javax.swing.JButton();
        btnchia = new javax.swing.JButton();
        btntru = new javax.swing.JButton();
        btncong = new javax.swing.JButton();
        btncong1 = new javax.swing.JButton();
        btntru1 = new javax.swing.JButton();
        btnnhan1 = new javax.swing.JButton();
        btnchia1 = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dia chi Server");

        jLabel2.setText("So 1");

        jLabel3.setText("So 2");

        jLabel4.setText("Ket qua");

        jLabel5.setText("Tu so a");

        jLabel6.setText("Mau so a");

        jLabel7.setText("Tu so b");

        jLabel8.setText("Mau so b");

        btnnhan.setText("*");
        btnnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhanActionPerformed(evt);
            }
        });

        btnchia.setText("/");
        btnchia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchiaActionPerformed(evt);
            }
        });

        btntru.setText("-");
        btntru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntruActionPerformed(evt);
            }
        });

        btncong.setText("+");
        btncong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncongActionPerformed(evt);
            }
        });

        btncong1.setText("+");
        btncong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncong1ActionPerformed(evt);
            }
        });

        btntru1.setText("-");
        btntru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntru1ActionPerformed(evt);
            }
        });

        btnnhan1.setText("*");
        btnnhan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhan1ActionPerformed(evt);
            }
        });

        btnchia1.setText("/");
        btnchia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchia1ActionPerformed(evt);
            }
        });

        btnthoat.setText("Thoat");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btncong1)
                        .addGap(18, 18, 18)
                        .addComponent(btntru1)
                        .addGap(18, 18, 18)
                        .addComponent(btnnhan1)
                        .addGap(18, 18, 18)
                        .addComponent(btnchia1)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmaua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmaub)
                                    .addComponent(txttub, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtdiachi)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtso2)
                                            .addComponent(txtso1))
                                        .addGap(26, 26, 26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtketqua, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtphandu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnnhan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnchia))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btncong)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btntru)))))
                        .addGap(45, 45, 45))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnthoat)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntru)
                    .addComponent(btncong))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchia)
                    .addComponent(btnnhan))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtketqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphandu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txttua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txttub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtmaua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmaub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncong1)
                    .addComponent(btntru1)
                    .addComponent(btnnhan1)
                    .addComponent(btnchia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnthoat)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncongActionPerformed
        // TODO add your handling code here:
        try {
            String diachi = txtdiachi.getText();
            Registry r = LocateRegistry.getRegistry(diachi, 1234);
            InterfaceCalc ic = (InterfaceCalc) r.lookup("rmiCalc");
            int so1 = Integer.parseInt(txtso1.getText());
            int so2 = Integer.parseInt(txtso2.getText());
            int c = ic.cong(so1, so2);
            txtketqua.setText(String.valueOf(c));
            txtphandu.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btncongActionPerformed

    private void btncong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncong1ActionPerformed
        // TODO add your handling code here:
        try {
            String diachi = txtdiachi.getText();
            Registry r = LocateRegistry.getRegistry(diachi, 1234);
            InterfaceCalc ic = (InterfaceCalc) r.lookup("rmiCalc");
            PhanSo a = new PhanSo(Integer.parseInt(txttua.getText()), Integer.parseInt(txtmaua.getText()));
            PhanSo b = new PhanSo(Integer.parseInt(txttub.getText()), Integer.parseInt(txtmaub.getText()));
            PhanSo c = ic.cong(a, b);
            rutgon(c);
//            txtketqua.setText(c.getTu() + "/" + c.getMau() + " = " + c.getTu() / c.getMau());
            txtphandu.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btncong1ActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btntruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntruActionPerformed
        // TODO add your handling code here:
        try {
            String diachi = txtdiachi.getText();
            Registry r = LocateRegistry.getRegistry(diachi, 1234);
            InterfaceCalc ic = (InterfaceCalc) r.lookup("rmiCalc");
            int so1 = Integer.parseInt(txtso1.getText());
            int so2 = Integer.parseInt(txtso2.getText());
            int c = ic.tru(so1, so2);
            txtketqua.setText(String.valueOf(c));
            txtphandu.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btntruActionPerformed

    private void btnnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhanActionPerformed
        // TODO add your handling code here:
        try {
            String diachi = txtdiachi.getText();
            Registry r = LocateRegistry.getRegistry(diachi, 1234);
            InterfaceCalc ic = (InterfaceCalc) r.lookup("rmiCalc");
            int so1 = Integer.parseInt(txtso1.getText());
            int so2 = Integer.parseInt(txtso2.getText());
            int c = ic.nhan(so1, so2);
            txtketqua.setText(String.valueOf(c));
            txtphandu.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnnhanActionPerformed

    private void btnchiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchiaActionPerformed
        // TODO add your handling code here:
        try {
            String diachi = txtdiachi.getText();
            Registry r = LocateRegistry.getRegistry(diachi, 1234);
            InterfaceCalc ic = (InterfaceCalc) r.lookup("rmiCalc");
            int so1 = Integer.parseInt(txtso1.getText());
            int so2 = Integer.parseInt(txtso2.getText());
            String[] c = ic.chia(so1, so2).split("@");
            txtketqua.setText(c[0]);
            txtphandu.setText(c[1]);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnchiaActionPerformed

    private void btntru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntru1ActionPerformed
        // TODO add your handling code here:
        try {
            String diachi = txtdiachi.getText();
            Registry r = LocateRegistry.getRegistry(diachi, 1234);
            InterfaceCalc ic = (InterfaceCalc) r.lookup("rmiCalc");
            PhanSo a = new PhanSo(Integer.parseInt(txttua.getText()), Integer.parseInt(txtmaua.getText()));
            PhanSo b = new PhanSo(Integer.parseInt(txttub.getText()), Integer.parseInt(txtmaub.getText()));
            PhanSo c = ic.tru(a, b);
            rutgon(c);
//            txtketqua.setText(c.getTu() + "/" + c.getMau() + " = " + c.getTu() / c.getMau());
            txtphandu.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btntru1ActionPerformed

    private void btnnhan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhan1ActionPerformed
        // TODO add your handling code here:
        try {
            String diachi = txtdiachi.getText();
            Registry r = LocateRegistry.getRegistry(diachi, 1234);
            InterfaceCalc ic = (InterfaceCalc) r.lookup("rmiCalc");
            PhanSo a = new PhanSo(Integer.parseInt(txttua.getText()), Integer.parseInt(txtmaua.getText()));
            PhanSo b = new PhanSo(Integer.parseInt(txttub.getText()), Integer.parseInt(txtmaub.getText()));
            PhanSo c = ic.nhan(a, b);
            rutgon(c);
//            txtketqua.setText(c.getTu() + "/" + c.getMau()+ " = " + c.getTu() / c.getMau());
            txtphandu.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnnhan1ActionPerformed

    private void btnchia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchia1ActionPerformed
        // TODO add your handling code here:
        try {
            String diachi = txtdiachi.getText();
            Registry r = LocateRegistry.getRegistry(diachi, 1234);
            InterfaceCalc ic = (InterfaceCalc) r.lookup("rmiCalc");
            PhanSo a = new PhanSo(Integer.parseInt(txttua.getText()), Integer.parseInt(txtmaua.getText()));
            PhanSo b = new PhanSo(Integer.parseInt(txttub.getText()), Integer.parseInt(txtmaub.getText()));
            PhanSo c = ic.chia(a, b);
            rutgon(c);
//            txtketqua.setText(c.getTu() + "/" + c.getMau()+ " = " + c.getTu() / c.getMau());
            txtphandu.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnchia1ActionPerformed

    public void rutgon(PhanSo ps){
        if (ps.getTu()%ps.getMau()== 0 ) {
            txtketqua.setText(ps.getTu() + "/" + ps.getMau()+ " = " + ps.getTu() / ps.getMau());
        } else {
            txtketqua.setText(ps.getTu() + "/" + ps.getMau());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rmiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rmiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rmiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rmiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rmiClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchia;
    private javax.swing.JButton btnchia1;
    private javax.swing.JButton btncong;
    private javax.swing.JButton btncong1;
    private javax.swing.JButton btnnhan;
    private javax.swing.JButton btnnhan1;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btntru;
    private javax.swing.JButton btntru1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtketqua;
    private javax.swing.JTextField txtmaua;
    private javax.swing.JTextField txtmaub;
    private javax.swing.JTextField txtphandu;
    private javax.swing.JTextField txtso1;
    private javax.swing.JTextField txtso2;
    private javax.swing.JTextField txttua;
    private javax.swing.JTextField txttub;
    // End of variables declaration//GEN-END:variables
}
